### ISSUE TITLE
instruction how to use the tool

### ISSUE THREAD

**Issue by nukropina** [rojo-rbx/rbxlx-to-rojo#28]
cannot find instruction how to use the tool, could we add some?

**Comment by Kampfkarren** [comment]
I can add some writing down later, but in about 4 days I'm going to brief on how to use it. For now, the tool should explain itself. Download the latest release, run it, and it'll walk you through how to use it.

**Comment by nukropina** [comment]
There is rbxlx-to-rojo.exe
is there a OS X binary ?

**Comment by Kampfkarren** [comment]
@nukropina I am trying to get a Mac binary as soon as possible, sorry for the wait.

**Comment by Kampfkarren** [comment]
Mac build is out! Download "rbxlx-to-rojo" on the releases page.
