### ISSUE TITLE
Compile issues with cargo

### ISSUE THREAD

**Issue by Wittiest** [rojo-rbx/rbxlx-to-rojo#29]
I ran:
`cargo install --git https://github.com/rojo-rbx/rbxlx-to-rojo`

After compilation, the terminal had this output:
`no binaries are available for install using the selected features`

I'm assuming this isn't expected behavior? There doesn't seem to be an executable provided for macOS in the releases, otherwise I would just use that.

Personally, I'm not familiar with rust, so please forgive me if I made a silly mistake here.

**Comment by Kampfkarren** [comment]
You need to specify the "cli" feature for it to build, that's kind of unintuitive though, I agree.

` cargo install --git https://github.com/rojo-rbx/rbxlx-to-rojo --features cli`

> There doesn't seem to be an executable provided for macOS in the releases, otherwise I would just use that.

Think you could build us one? ;)

**Comment by Wittiest** [comment]
Thanks! Binary sent via discord.
