### ISSUE TITLE
Just closes instantly

### ISSUE THREAD

**Issue by Klicer** [rojo-rbx/rbxlx-to-rojo#31]
Closes as soon as you choose a place file and doesn't do anything

EDIT: forgot to mention it worked perfectly earlier

**Comment by Kampfkarren** [comment]
Is there scripts in the place? If not, https://github.com/rojo-rbx/rbxlx-to-rojo/issues/26

**Comment by Klicer** [comment]
It's when you choose a place file it instantly closes. The place is not empty. 
How do I run it through a powershell window?

**Comment by Kampfkarren** [comment]
@Klicer Shift right-click the folder you downloaded it to in the Windows file explorer, then type `.\rbxlx-to-rojo.exe` and tell me what it says.

**Comment by Klicer** [comment]
![powershell_PHlYuTxS7x](https://user-images.githubusercontent.com/51763508/62928370-19298500-bdc1-11e9-9bec-578c775fc534.png)

**Comment by Kampfkarren** [comment]
You're using rbxl, not rbxlx.

**Comment by Klicer** [comment]
I just renamed it from rbxl to rbxlx, how do you export a game as rbxlx?

**Comment by Kampfkarren** [comment]
When you're saving the place, change the file type to rbxlx.

**Comment by Klicer** [comment]
thanks i didn't realize there was that option (although idk how it worked for me for the first time I used it) now it works perfectly. my bad
