### ISSUE TITLE
Only Partially Works for Certain Place

### ISSUE THREAD

**Issue by vastqud** [rojo-rbx/rbxlx-to-rojo#35]
Hello, so I tried using this for my main game and it only partially works. I don't get any errors when running the .exe.

It skips over a lot of scripts, and almost every modulescript isn't included. Also, for this particular place, a default.project JSON file is never created. I tried it out on a different game of mine and it worked just fine -- every script was included and everything worked as intended. It just seems that for this one place, certain files are not created.

Could it have something to do with the file size? It's about 50,000 kilobytes. Smaller files work without any problems.

If you need any more information for debugging or correcting any mistake that I might be making, let me know. Thanks.

**Comment by Kampfkarren** [comment]
Most likely your place has data types that rbx-xml doesn't support.

Can you follow these instructions and let me know what it says?

> Shift right-click the folder you downloaded it to in the Windows file explorer, then type `.\rbxlx-to-rojo.exe` and tell me what it says.

**Comment by vastqud** [comment]
Here's what it says after I ran through the entire process with the problematic place:
![image](https://user-images.githubusercontent.com/66101476/83216032-4ff53f80-a136-11ea-95f4-730591dfb032.png)

**Comment by Kampfkarren** [comment]
That would make sense--you can't put a slash in a filename. Let me know if changing it fixes that.

**Comment by vastqud** [comment]
Yep, it works now!
