### ISSUE TITLE
Saving only StarterGui and Starterplayer

### ISSUE THREAD

**Issue by Gamerdude7820** [rojo-rbx/rbxlx-to-rojo#38]
I need it to save my replicatedstorage and serverscriptservice scripts. this is not helpful.
![Image10930942](https://user-images.githubusercontent.com/76228770/102662046-0577f680-414c-11eb-9d98-8866fe294a2c.PNG)

**Comment by Kampfkarren** [comment]
Can you do me a favor and run rbxlx-to-rojo in PowerShell and see what it spits out?

Shift right-click the folder you downloaded it to in the Windows file explorer, then type .\rbxlx-to-rojo.exe and tell me what it says.

**Comment by Mixu78** [comment]
This is due to windows not supporting dots in folder names.

![image](https://user-images.githubusercontent.com/45693771/102685395-ec715300-41e8-11eb-866f-50a4cb0bccd4.png)

**Comment by Kampfkarren** [comment]
:+1: Not a fault of rbxlx-to-rojo then.
