### ISSUE TITLE
Cannot run rbxlx-to-rojo file on MacOS

### ISSUE THREAD

**Issue by CodeJellybeans** [rojo-rbx/rbxlx-to-rojo#39]
I downloaded the file and double clicked but it didn't open and returned an error.
I also tried running in terminal(./rbxlx-to-rojo) but it said "command not found".
**HELP ME PLEASE ;-;**
OS: MacOS Big Sur

**Comment by Kampfkarren** [comment]
What was the error?

I don't have a Mac so it's very difficult for me to help.

**Comment by CodeJellybeans** [comment]
> What was the error?
> 
> I don't have a Mac so it's very difficult for me to help.

The file is opened as a document file and the error says it's not encoded

**Comment by VladPutinEu** [comment]
> What was the error?
> 
> I don't have a Mac so it's very difficult for me to help.

If I'm wrong you were using a Mac at [RDC 2019.](https://www.youtube.com/watch?v=czlvzEyhaBc) 😏 Unless that was provided by Roblox or you don't have it anymore.

**Comment by Kampfkarren** [comment]
Yeah, that was just a laptop they had for presentations 😛 

The Mac build was provided for by someone else.

**Comment by VladPutinEu** [comment]
Well, you could always buy a Mac or find someone who has one and will contribute to this project. Or, you could just use Hackintosh, but I will not condone that for obvious reasons.

**Comment by chllamas** [comment]
In the terminal, go to where your rbx-to-rojo file is. Type in
`chmod +x rbx*`
Note:  The asterisk at the end of rbx is autofill, if you have other files that start with rbx then type the whole file name.

Now you could run the command
`./rbx*`

Also, in case the popup for the file selecting glitches for you like it did for me, I right clicked the .rbxlx file and hit "Rename" then it allowed me to 'Open' the file.  Hope this helps

**Comment by Kampfkarren** [comment]
I'm going to be building a new release on Mac soon, but this isn't enough information to reasonably act on.

**Comment by gagbaghdas** [comment]
Ping on this
