### ISSUE TITLE
Rbxlx-to-rojo isn't correctly installing

### ISSUE THREAD

**Issue by FrostDracony** [rojo-rbx/rbxlx-to-rojo#43]
Hi, I recently wanted starting working with Rojo, I already have a game where I code an plugin, but for some strange reasons the rbxlx-to-rojo isn't accurately porting my game to rojo. What I should see:
![image](https://user-images.githubusercontent.com/60100684/106331310-fc1e9580-6284-11eb-9c30-21501a4dc8ab.png)
And what I see:
![Code_VhZxEmwIF3](https://user-images.githubusercontent.com/60100684/106331346-0fc9fc00-6285-11eb-8569-515d7746d5bc.png)
I understand the rbxlx.lock file and the rojo file, but where is the default.project.json file? I don't see it and I don't know what should be there, so any idea whats happening?

While I was importing, I only selected one  place file and the target folder, and I don't see any errors. Then, my place has some scripts: In my Workspace and in my StarterGui, so the bug that occurs when I don't have any scripts shouldn't occure. What's the problem?

**Comment by Kampfkarren** [comment]
Run rbxlx-to-rojo in powershell and see if any errors come up.

**Comment by FrostDracony** [comment]
Ops, I missclicked

And what do you mean by running it in powershell? I mean what command do I need to use? only "run" or "init"?

**Comment by Kampfkarren** [comment]
Open a powershell window where the program is, then type `.\rbxlx-to-rojo.exe` and use it.

**Comment by FrostDracony** [comment]
Ok, now I feel just dumb...
Yes, there is actually an error ( I think it's an error?)
```
thread 'main' panicked at 'can't create file "StarterGui\\ImportedFromOldPlace\\Model\\GameHelperPlugin\\CustomizePluginMenu\\ThanksGui\\ThanksGuiBackGround\\ContinueButtonBackGround\\Shader\\ConitnueButton\\init.meta.json": Os { code: 3, kind: NotFound, message: "Le chemin d’accès spécifié est introuvable." }', src\filesystem.rs:90:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Hope it helps

P.S.:Yes, this little line, `Le chemin d’accès spécifié est introuvable`, it's written in French. If I just ask deepl.com to translate it to English, the meaning is the same as `The specified path cannot be found`

**Comment by Kampfkarren** [comment]
Interesting.

Can you try creating the *folders* (not the last file) that it's asking you for? That is in fact a bug, but I want to see if you can fix it on your own in the meantime.

**Comment by Sci-Punk** [comment]
Having the same problem right now, what folder should I create?

`PS C:\Users\ishen> Downloads/rbxlx-to-rojo.exe
[2021-03-22T15:59:52Z INFO  rbxlx_to_rojo] rbxlx-to-rojo 0.1.0
[2021-03-22T15:59:52Z INFO  rbxlx_to_rojo] Select a place file.
[2021-03-22T16:00:05Z INFO  rbxlx_to_rojo] Opening place file
[2021-03-22T16:00:05Z INFO  rbxlx_to_rojo] Decoding place file, this is the longest part...
[2021-03-22T16:00:05Z INFO  rbxlx_to_rojo] Select the path to put your Rojo project in.
[2021-03-22T16:00:12Z INFO  rbxlx_to_rojo] Starting processing, please wait a bit...
thread 'main' panicked at 'can't create file "ServerScriptService\\Day/Night Cycle.server.lua": Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." }', src\filesystem.rs:90:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
PS C:\Users\ishen>`

**Comment by Kampfkarren** [comment]
Remove any slashes and other funky characters from your script and folder names. Files with weird symbols can't be added. Try to keep it to alphanumeric.
