### ISSUE TITLE
Rbxlx-To-Rojo closing with no errors

### ISSUE THREAD

**Issue by ThatCodingGuy8** [rojo-rbx/rbxlx-to-rojo#45]
Hello, whenever I try to convert my rbxlx file, it says "decoding file" and then closes itself soon after with no error. I tried replacing optionalcoordinates with grep to no avail.

Im on a windows 10 machine

**Comment by Kampfkarren** [comment]
Shift right-click the folder you downloaded it to in the Windows file explorer, then type .\rbxlx-to-rojo.exe and tell me what it says.

**Comment by MajenBej** [comment]
I have the same problem.

**Comment by ThatCodingGuy8** [comment]
Latest release fixed the issue
