### ISSUE TITLE
I can't open rbxlx-to-rojo-macos

### ISSUE THREAD

**Issue by EvansSource** [rojo-rbx/rbxlx-to-rojo#46]
Please help! I've been watching a tutorial on how to set up rojo, one of the steps is to open this file and when i open it i just get a text edit with a bunch characters and stuff, i am on catalina os fyi

**Comment by EvansSource** [comment]
also the tutorial was on windows cause i couldn't find a single one on mac

**Comment by Kampfkarren** [comment]
Can you try opening a terminal at the location, then going `chmod +x rbxlx-to-rojo-macos`?

**Comment by EvansSource** [comment]
location for the folder that contains the rojo file or the file itself?

**Comment by Kampfkarren** [comment]
For the rbxlx-to-rojo-macos file.

**Comment by EvansSource** [comment]
just says Permission denied, nothing else

**Comment by EvansSource** [comment]
it showed: -bash: /Users/BLANKEDFORPRIVACY/Documents/test/Projects/rojostuff/rbxlx-to-rojo-macos: Permission denied

**Comment by Kampfkarren** [comment]
I'm, not totally sure. That's supposed to make it an executable, and I don't have a Mac to test on.

**Comment by EvansSource** [comment]
Nevermind it worked! Thank you!
