### ISSUE TITLE
Unknown value type name "OptionalCoordinateFrame"

### ISSUE THREAD

**Issue by windingtheropes** [rojo-rbx/rbxlx-to-rojo#48]
When trying to convert a place file, I get this error, I have tried both .rbxl and .rbxlx formats and this error has kept occuring.
![image](https://user-images.githubusercontent.com/17016045/120700111-3db38d00-c47f-11eb-83b2-8ef41830e1df.png)

**Comment by Kampfkarren** [comment]
It's not an error. It's a warning. You can easily ignore it.

**Comment by Kampfkarren** [comment]
If your rbxlx-to-rojo is closing, it's not due to this--there's a separate error that is forcing rbxlx-to-rojo to close (because its error managing is bad). Most likely you have a folder/script with funky names.

**Comment by windingtheropes** [comment]
what would these names entail?

**Comment by windingtheropes** [comment]
What types of names would cause errors? I've removed slashes that i've found and filled empty names, still not getting to the folder export point..

**Comment by Kampfkarren** [comment]
Shift right-click the folder you downloaded it to in the Windows file explorer, then type .\rbxlx-to-rojo.exe and tell me what it says.

**Comment by windingtheropes** [comment]
![image](https://user-images.githubusercontent.com/17016045/120832272-765e6f80-c52e-11eb-9a98-00f0b83d55c2.png)
then brings up the dialog to open the place file

**Comment by Kampfkarren** [comment]
What happens if you use an rbxlx instead?

**Comment by windingtheropes** [comment]
by removing those two mystery symbols i got it to work
