### ISSUE TITLE
rbxlx-ro-rojo not building my whole game, only workspace

### ISSUE THREAD

**Issue by RemielDev** [rojo-rbx/rbxlx-to-rojo#50]
Building the file took seconds and the only error was: Unknown value type name "OptionalCoordinateFrame" in Roblox XML model file. Found in property Workspace.WorldPivotData.

**Comment by Kampfkarren** [comment]
Shift right-click the folder you downloaded it to in the Windows file explorer, then type .\rbxlx-to-rojo.exe and tell me what it says.

**Comment by RemielDev** [comment]
Unknown value type name "OptionalCoordinateFrame" in Roblox XML model file. Found in property Model.WorldPivotData.

**Comment by Kampfkarren** [comment]
If that's the *only* message, then the newest rbxlx-to-rojo shouldn't have the issue. That's just a warning.

**Comment by RemielDev** [comment]
Well, that's the message I get when during the first step of the main exe runner. How would I type  .\rbxlx-to-rojo.exe on the file holding the result of the roblox to rojo runner?

**Comment by Kampfkarren** [comment]
Using PowerShell will show you the other error messages, since it's existing right as they get them.

> Shift right-click the folder you downloaded it to in the Windows file explorer, then type .\rbxlx-to-rojo.exe and tell me what it says.

**Comment by RemielDev** [comment]
Looks like the build hasn't been completed at all. Here is the error;
![image](https://user-images.githubusercontent.com/81453063/135026404-5f6fb20d-8d95-442e-84d5-c41a40743f80.png)

**Comment by Kampfkarren** [comment]
Looks like you have some funky directory names! I would recommend keeping everything just to alphabet, numbers, and spaces/underscores. Windows can't handle much more than that.
