### ISSUE TITLE
After Using Rbxlx To Rojo, I get errors. I tried starting the server, but I get this

### ISSUE THREAD

**Issue by 830008** [rojo-rbx/rbxlx-to-rojo#51]
![Code_CsZYuPxJbf](https://user-images.githubusercontent.com/55303069/145654606-50721de4-51fc-425d-a576-079f4c700477.png)

**Comment by Kampfkarren** [comment]
Not an rbxlx-to-rojo bug, sticking to your one on https://github.com/rojo-rbx/rojo/issues/509
