### ISSUE TITLE
The filename, directory name, or volume label syntax is incorrect.

### ISSUE THREAD

**Issue by HissingSoldier** [rojo-rbx/rbxlx-to-rojo#52]
Hello, I am trying to convert a fairly big game and keep getting the same error.

Here is a screenshot:

![image](https://user-images.githubusercontent.com/67211429/150043393-ef55302f-1d64-4f57-aee2-3733fca1c34e.png)

I have looked at the other person that had the same problem but it seems as though he fixed the problem by reenabling scripts, but I don't have any disabled scripts.

Any and all help is appreciated!

**Comment by Kampfkarren** [comment]
This is a common error, and the problem is that rbxlx-to-rojo doesn't just tell you what it is.

Something in your game that is being exported, such as a folder or a script, has a name Windows can't create. Look for things like colons, etc.
