### ISSUE TITLE
Only a tiny bit of the game converts

### ISSUE THREAD

**Issue by ncax** [rojo-rbx/rbxlx-to-rojo#53]
When I tried using rbxlx-to-rojo on my game, (which I downloaded directly from the roblox website) it only extracted one folder from the workspace and nothing else. Is this a bug or just me being dumb and not doing something right?

**Comment by Kampfkarren** [comment]
It's a bug that rbxlx-to-rojo doesn't give you more info, but it also means something in your place is wrong: https://github.com/rojo-rbx/rbxlx-to-rojo/issues/50
