### ISSUE TITLE
Can't create default.project.json

### ISSUE THREAD

**Issue by FSXplay** [rojo-rbx/rbxlx-to-rojo#54]
The video below shows what happened:

https://user-images.githubusercontent.com/95726321/154827997-87df5681-baa9-4854-94d1-8f61d6c1521b.mp4

As you can see, after running rbxlx-to-rojo, it didn't create default.project.json, and some scripts in my game weren't appear in the folder.

**Comment by Kampfkarren** [comment]
It's a bug that rbxlx-to-rojo doesn't give you more info, but it also means something in your place is wrong: https://github.com/rojo-rbx/rbxlx-to-rojo/issues/50

**Comment by FSXplay** [comment]
Is it because I have some disabled scripts?

**Comment by FSXplay** [comment]
Can you explain what is wrong in my place?

**Comment by Kampfkarren** [comment]
Check the instructions I gave the guy in #50 about how to find his error.

99% of the time, you have a folder/script with a name that Windows can't create, such as because it has special characters like parentheses.
