### ISSUE TITLE
rbxlx-to-rojo fails to write to the folder

### ISSUE THREAD

**Issue by splatboy20081** [rojo-rbx/rbxlx-to-rojo#56]
After following all the instructions and selecting all of the file paths, the following Rust error happens:

![cmd_QgsuPYzlJR](https://user-images.githubusercontent.com/64037464/163086474-e09093ac-7dd0-4743-9a2a-fd5a7e921328.png)

I have correctly followed the instructions, and am aware that this might be considered dead.

OS: Windows 11

**Comment by splatboy20081** [comment]
Might just be a general problem with Win11 though

**Comment by Kampfkarren** [comment]
It's a bug that rbxlx-to-rojo doesn't give you more info, but it also means something in your place is wrong: https://github.com/rojo-rbx/rbxlx-to-rojo/issues/50
