### ISSUE TITLE
Decoding currently broken

### ISSUE THREAD

**Issue by kingpada** [rojo-rbx/rbxlx-to-rojo#58]
I have been getting this type of error all month. I do not know what the issue is but yeah.
![image](https://user-images.githubusercontent.com/79657836/166244809-dca6699a-6534-4105-833e-1099e646cd2c.png)

**Comment by Kampfkarren** [comment]
You can't have a script with a slash in the name. You need to rename it.

**Comment by kingpada** [comment]
![image](https://user-images.githubusercontent.com/79657836/166697079-04c1c078-756d-4115-9b72-ae386e2c603e.png)
that does this mean?

**Comment by Kampfkarren** [comment]
You have a container, like a folder, with a bad name.

rbxlx-to-rojo can't make folders/filenames with special characters that Windows doesn't support. Remove slashes, quotes, etc.

**Comment by kingpada** [comment]
would underscores and dashes affect it
