### ISSUE TITLE
Project json not being created after processing

### ISSUE THREAD

**Issue by ArchedHeart** [rojo-rbx/rbxlx-to-rojo#67]
Firstly I'm getting this warning when uploading:
![image](https://user-images.githubusercontent.com/87141676/210099380-9b87f70f-c23a-4fc6-a1bb-d75c1bf2ac20.png)
Then when I checked the rojo file the project json had not been created and if I'm honest it doesn't really specify where these unidentified property values are.
![image](https://user-images.githubusercontent.com/87141676/210099683-b21d1a7e-5021-4aff-82d4-5977fe928d5e.png)
the JSON file should be in here.

**Comment by Kampfkarren** [comment]
Those are warnings. They aren't relevant. What is happening is it's hitting something it ACTUALLY can't process, then crashing. Run the program inside a command prompt and check the new error message. Usually it's something with a bad name.
