### ISSUE TITLE
Fails to convert fully, doesn't output to .log file

### ISSUE THREAD

**Issue by ArtiTice** [rojo-rbx/rbxlx-to-rojo#74]
**Found a temporary solution, scroll down to second comment of mine to see solution.**

~~I tried looking for similar issues but couldn't find much that quite fit this issue. Unsure if I'll get a response since this repo seems pretty inactive but I thought it'd be worth a shot.~~

**Whenever I use the .exe converter on a .rbxl or .rbxlx file, it outputs this text in console before I select the folder to store the converted files.** 
"[2023-11-01T09:05:11Z WARN  rbx_xml::deserializer] Unknown value type name "SecurityCapabilities" in Roblox XML model file. Found in property Workspace.Capabilities.
[2023-11-01T09:05:11Z WARN  rbx_xml::deserializer] Unknown value type name "UniqueId" in Roblox XML model file. Found in property Workspace.HistoryId.
[2023-11-01T09:05:11Z WARN  rbx_xml::deserializer] Unknown value type name "OptionalCoordinateFrame" in Roblox XML model file. Found in property Workspace.WorldPivotData.
[2023-11-01T09:05:12Z WARN  rbx_xml::deserializer] Unknown value type name "Font" in Roblox XML model file. Found in property TextLabel.FontFace."
After I select the folder, it quickly only converts my place partially with only some files and a lot of necessary project files are still missing. The .log also only has the line: "Starting processing, please wait a bit...

![image](https://github.com/rojo-rbx/rbxlx-to-rojo/assets/83902122/5af70342-8c56-44eb-92dc-c2b4a7fa40ef)
![image](https://github.com/rojo-rbx/rbxlx-to-rojo/assets/83902122/5537b57b-9c2b-4c57-93c3-980562e85abc)

~~Is there any solutions? I'm using the latest version of the converter.~~

**Comment by fisherdog4** [comment]
Same issue with similar warnings

**Comment by NeonPalm** [comment]
Make sure there are no special characters not supported by windows within any of the paths generated by rbxlx-to-rojo in your roblox game.
Personally had some issues with script names having ":" and a path name containing "/" after some trial and error.

**Comment by MiaGobble** [comment]
This is still an issue, hoping this gets fixed

**Comment by ArtiTice** [comment]
> Make sure there are no special characters not supported by windows within any of the paths generated by rbxlx-to-rojo in your roblox game. Personally had some issues with script names having ":" and a path name containing "/" after some trial and error.

I recently revisited using this converter application and found this was actually a partial solution to get the converter to work. The console for the converter would show a error message sometimes hinting at an invalid name, and some script names had "/" characters or other special characters in them that caused it to be error. After renaming those scripts I got the converter to process successfully.

I found that the console would close super fast after it errored, but if you record the console's window in like OBIS, you can replay what the message was, here's example error message screenshots. 

**One script(QuentySoftShutdown) had way too many child objects and folders, so I removed that from the place file since I only care about saving scripts that I wrote myself:** 
![image](https://github.com/rojo-rbx/rbxlx-to-rojo/assets/83902122/6fcef98a-79bc-44b8-8b2c-ed73bd3eb9fb)
![image](https://github.com/rojo-rbx/rbxlx-to-rojo/assets/83902122/81725266-a242-4067-8475-d28e5e3f3a14)

**Invalid character error:** 
![image](https://github.com/rojo-rbx/rbxlx-to-rojo/assets/83902122/de2a6962-c3ee-4a0f-ad70-4644ba578d8d)


Hope this info helps someone that runs into a similar issue.
